/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'max' at '10.05.17 12:12' with Gradle 2.14.1
 *
 * @author max, @date 10.05.17 12:12
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
